name: dev-storages
services:
  broker:
    image: apache/kafka:3.9.0
    container_name: kafka_broker
    ports:
      - "9092:9092"
    volumes:
      - broker-data:/data

  cache:
    image: redis:7.4.1-alpine3.20
    container_name: redis_cache
    ports:
      - "6379:6379"
    volumes:
      - cache-data:/data

  rdb:
    image: postgres:17.2-alpine3.21
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - rdb-data:/var/lib/postgresql

volumes:
  cache-data:
  broker-data:
  rdb-data:
